### ISSUE TITLE
Year calculation for the yearly view

### ISSUE THREAD

**Issue by kev-ng** [tienphaw/LifeProgress#4]
It seems that the "Your XXth year" can be a year off if not taken into account the birth month. Any chance to improve it? Great work anyways!

**Comment by phamfoo** [comment]
> if not taken into account the birth month

not sure what you mean, can you elaborate?

**Comment by kev-ng** [comment]
Oh sure. I think it's just me getting confused about the year and we can close the issue.

Just to explain Eg.

Let's say my birthday is on 2000 Dec 1. Today, I would be 22 years old (not 23 yet).

The label at the top of the year view for today is:

> Your 23rd year
> 51.9%

The confusion comes from the fact that I could be thinking about 22 years instead of 23. But it's also correct to say it's 51.9% towards 23rd year.

**Comment by phamfoo** [comment]
I can see why it can be confusing, not sure what else to call it though. Suggestions are welcome!
