### ISSUE TITLE
Feature Request: add additional time metrics 

### ISSUE THREAD

**Issue by kelos-01** [tienphaw/LifeProgress#5]
Just a suggestion if, hours days and minutes &/or even seconds can be added.

**Comment by phamfoo** [comment]
Thanks for the suggestion.
The idea for the app comes from this blog post called ["Your life in weeks"](https://waitbutwhy.com/2014/05/life-weeks.html). I also find that the week is the ideal unit for your life/year progress. This is not something I want to add to the app. Sorry.
